### ISSUE TITLE
Low power mode

### ISSUE THREAD

**Issue by PeterKremsner** [stm32duino/VL53L3CX#13]
As far as i am aware of, this sensor supports a low power mode where it doesn't full ranging, but it can create an interrupt when an object is detected in a certain proximity.

By searching the library i saw that there are functions implemented that appear to configure the sensor in such a way, however I am not able to fully understand this. Are there any examples how this library could be used for this low power mode?

**Comment by cparata** [comment]
Hello @PeterKremsner ,
I guess that you refer to ULD mode, as described in [this](https://www.st.com/resource/en/application_note/an5769-using-the-vl53l3cx-under-ultralowpower-mode-stmicroelectronics.pdf) document. Unfortunately, we did not port this version of the driver in the Arduino library, so only bare driver is supported in the Arduino environment.
Best Regards,
Carlo

**Comment by PeterKremsner** [comment]
Hello Carlo,

thank you for your response!
Yes i was refering to the ULP mode. Is it on the roadmap for future versions?

best regards,
Peter

**Comment by cparata** [comment]
Hello @PeterKremsner ,
unfortunately not. It is not in our roadmap. Anyway, any contribution to improve the library is welcome. 
Best Regards,
Carlo
