### ISSUE TITLE
People counter on Arduino MKR1000

### ISSUE THREAD

**Issue by Ligas10105** [stm32duino/VL53L3CX#8]
Is it possible to make a people counter using the VL53L3CX sensor on the Arduino MKR 1000 board?

**Comment by cparata** [comment]
Unfortunately, at the moment the people counter demonstration is available only for VL53L1X component and you can find the implementation [here](https://github.com/stm32duino/X-NUCLEO-53L1A1/blob/master/examples/X_NUCLEO_53L1A1_People_Counting/X_NUCLEO_53L1A1_People_Counting.ino). Currently, there is not the possibility to implement it also for VL53L3CX as explained [here](https://github.com/stm32duino/VL53L3CX/issues/5).
Best Regards,
Carlo

**Comment by Ligas10105** [comment]
I understand.  Thank you for the quick reply
